name: Maven Package and Release


on:
  push:
    branches: [ "auto_build" ]
  pull_request:
    branches: [ "auto_build" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Install Dependencies
      run: |
        chmod +x install_deps.sh
        ./install_deps.sh

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create Release and Upload Artifacts
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: Release ${{ github.run_number }}
        draft: false
        prerelease: true

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload *.jar
      uses: actions/upload-artifact@v2
      with:
        name: Elaina (other versions)
        path: target/*.jar
